// <auto-generated />
using IGraficaIES.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IGraficaIES.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251202170442_crear_bd")]
    partial class crear_bd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IGraficaIES.ProfesorExtendido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ECivil")
                        .HasColumnType("bigint");

                    b.Property<int>("Estatura")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("ProfesorFuncionarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorFuncionarioId")
                        .IsUnique();

                    b.ToTable("ProfesoresExtendidos");
                });

            modelBuilder.Entity("_2HerenciaSimpleIES.ProfesorFuncionario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnyoIngresoCuerpo")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DestinoDefinitivo")
                        .HasColumnType("bit");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TipoMedico")
                        .HasColumnType("bigint");

                    b.Property<long>("TipoProfesor")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ProfesoresFuncionarios");
                });

            modelBuilder.Entity("IGraficaIES.ProfesorExtendido", b =>
                {
                    b.HasOne("_2HerenciaSimpleIES.ProfesorFuncionario", null)
                        .WithOne("ProfesorExtendido")
                        .HasForeignKey("IGraficaIES.ProfesorExtendido", "ProfesorFuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2HerenciaSimpleIES.ProfesorFuncionario", b =>
                {
                    b.Navigation("ProfesorExtendido")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
